spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key:
        secret-key:
      s3:
        bucket:
  security:
    user:
      name:
      password:
  datasource:
    url: jdbc:postgresql://postgres:5432/{dbName}
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    com.logistic.orders: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true

jwt:
  secret:
  expiration:

server:
  port: 8080
