spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ordersdb
    username: postgres_orders_app
    password: postgres_password_app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
